In [1]:
import torch
torch.__version__

'1.13.1+cu117'

## Tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [5]:
scalar.item()
# Gets the scalar value as a number (works only for scalars/0-dim)

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [15]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2951, 0.5166, 0.0406, 0.4935],
         [0.5159, 0.6928, 0.5553, 0.6677],
         [0.9706, 0.7607, 0.0320, 0.3819]]),
 torch.float32)

## Zeros and ones

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Ranges

In [18]:
zero_to_ten_dep = torch.range(0, 10) # deprecated

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_7097/1140756805.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_dep = torch.range(0, 10) # deprecated


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Like tensors

In [19]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Datatypes

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
# dtype=None => float_32, device=None => default tensor, requires_grad=True => operations performed are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device
# These three attrbiutes can help a lot with finding and fixing issues

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16) # or torch.half
float_16_tensor.dtype

torch.float16

## Tensor operations

In [23]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [26]:
tensor += 10
tensor

tensor([1, 2, 3])

In [27]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [28]:
tensor * tensor #element-wise matrix multiplication

tensor([1, 4, 9])

In [29]:
torch.matmul(tensor, tensor)
# equivalently, tensor @ tensor

tensor(14)

## Shape errors

In [30]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=torch.float32)
tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [31]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [32]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [33]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [34]:
# Short form for function
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Matrices in linear layers

In [36]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
print(x.shape)
print(output.shape)

torch.Size([3, 2])
torch.Size([3, 6])


In [37]:
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

## Aggregation

In [38]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(x.min())
print(x.max())
try:
    print(x.mean())
except:
    print('Needs the float datatype')
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
Needs the float datatype
tensor(45.)
tensor(450)


In [40]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [41]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

## Changing datatypes

In [43]:
tensor = torch.arange(10., 100., 10.) # without decimal points, int64
tensor.dtype

torch.float32

In [44]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [45]:
tensor_float16.dtype, tensor.dtype

(torch.float16, torch.float32)

In [46]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Size manipulation

In [47]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [48]:
x_reshaped = x.reshape(1, 7) # x_reshaped may share data with x
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z = x.view(1, 7) # z shares data with x. if x is changed, so is z
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [50]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [51]:
z[:, 0] = 5

In [52]:
z, x, x_reshaped

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([5., 2., 3., 4., 5., 6., 7.]),
 tensor([[5., 2., 3., 4., 5., 6., 7.]]))

In [53]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [54]:
x_stacked_1 = torch.stack([x, x, x, x], dim=1)
x_stacked_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [55]:
print(x_reshaped)
print(x_reshaped.shape)
x_squeezed = torch.squeeze(x_reshaped) # removes dimensions with shape 1
print(x_squeezed)
print(x_squeezed.shape)

tensor([[5., 2., 3., 4., 5., 6., 7.]])
torch.Size([1, 7])
tensor([5., 2., 3., 4., 5., 6., 7.])
torch.Size([7])


In [57]:
print(x_squeezed)
print(x_squeezed.shape)
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0) # where to add a dim of shape 1
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([5., 2., 3., 4., 5., 6., 7.])
torch.Size([7])
tensor([[5., 2., 3., 4., 5., 6., 7.]])
torch.Size([1, 7])


In [59]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = torch.permute(x_original, (2, 0, 1))
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [60]:
# Or,
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # returns a view
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing

In [61]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
print(x[0])
print(x[0][0])
print(x[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [63]:
x[:, 0]

tensor([[1, 2, 3]])

In [65]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [66]:
x[:, 1, 1]

tensor([5])

In [67]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch and NumPy

In [83]:
import numpy as np
array = np.arange(1.0, 8.0) # default type float64
tensor = torch.from_numpy(array) # shares data with the array
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
tensor = tensor + 1
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [79]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
numpy_tensor = numpy_tensor + 1
numpy_tensor, tensor

(array([2., 2., 2., 2., 2., 2., 2.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [86]:
# Note that modifications aren't reflected due to reassignment

## Reproducibility

In [87]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2012, 0.1478, 0.3702, 0.1441],
        [0.1284, 0.2582, 0.7732, 0.1060],
        [0.6737, 0.3027, 0.9716, 0.3592]])
tensor([[0.6261, 0.9557, 0.0057, 0.6767],
        [0.2114, 0.3975, 0.4007, 0.9157],
        [0.0821, 0.8882, 0.4257, 0.2228]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # comment it out and it won't work
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPUs

In [91]:
!nvidia-smi

Thu Dec 22 12:39:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P8     4W /  N/A |    196MiB /  4096MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [92]:
torch.cuda.is_available()

True

In [93]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [94]:
torch.cuda.device_count()

1

In [95]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [96]:
tensor_on_gpu.numpy()
# NumPy doesn't use GPU, so can't share data, hence, error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [97]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [98]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

In [99]:
rand_tensor = torch.rand(size=(7, 7))
rand_tensor, rand_tensor.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

In [102]:
rand_tensor_1 = torch.rand(size=(1, 7))
rand_prod = torch.mm(rand_tensor, rand_tensor_1.T)
rand_prod, rand_prod.shape

(tensor([[1.9915],
         [1.4538],
         [1.4906],
         [2.0956],
         [2.1863],
         [0.7820],
         [1.9173]]),
 torch.Size([7, 1]))

: 